crop_file_content: |
  Maize
  7000000         : Number of plants per hectare
  6               : Calendar Days: from sowing to emergence
  108             : Calendar Days: from sowing to maximum rooting depth
  155             : Calendar Days: from sowing to start senescence
  180             : Calendar Days: from sowing to maturity
  65              : Calendar Days: from sowing to flowering
  12              : Length of the flowering stage (days)
  65              : Building up of Harvest Index starting at flowering (days)
  0.30            : Minimum effective rooting depth (m)
  2.00            : Maximum effective rooting depth (m)

point:
  latitude: 45.0
  longitude: 25.0

seasons:
  - simulation_start: "2024-03-01"
    simulation_end: "2024-09-30"
    growing_season_start: "2024-04-01"
    growing_season_end: "2024-09-15"

soils:
  - - thickness: 0.3
      sat: 50.0
      fc: 35.0
      wp: 15.0
      ksat: 500.0
      penetrability: 100.0
      gravel: 0.0
      wc: 25.0
      ec: 0.5

fertility_stress: 0
gwt_depth: 2.0
gwt_ec: 0.0
