project
      7.1       : AquaCrop Version (August 2023)
      1         : Year 1
45017         : First day simulation (April 1, 2024)
45137         : Last day simulation (July 30, 2024)
45026         : First day cropping (April 10, 2024)
45132         : Last day cropping (July 25, 2024)
-- 1. Climate (CLI) file
   project.CLI
   './'
   1.1 Temperature (Tnx or TMP) file
   project.Tnx
   './'
   1.2 Reference ET (ETo) file
   project.ETo
   './'
   1.3 Rain (PLU) file
   project.PLU
   './'
   1.4 CO2 file
   MaunaLoa.CO2
   'SIMUL/'
-- 2. Calendar (CAL) file
   project.CAL
   './'
-- 3. Crop (CRO) file
   Maize.CRO
   './'
-- 4. Irrigation (IRR) file
   (None)
   (None)
-- 5. Management (MAN) file
   project.MAN
   './'
-- 6. Soil (SOL) file
   project.SOL
   './'
-- 7. Groundwater (GWT) file
   project.GWT
   './'
-- 8. Initial conditions (SW0) file
   project.SW0
   './'
-- 9. Off-season (OFF) file
   (None)
   (None)
-- 10. Field data (OBS) file
   (None)
   (None)
