project
      7.1       : AquaCrop Version (August 2023)
      1         : Year number of cultivation (Seeding/planting year)
45017         : First day of simulation period (April 1, 2024)
45137         : Last day of simulation period (July 30, 2024)
45026         : First day of cropping period (April 10, 2024)
45132         : Last day of cropping period (July 25, 2024)
-- 1. Climate (CLI) file
   project.CLI
   './'
   1.1 Temperature (Tnx or TMP) file
   project.Tnx
   './'
   1.2 Reference ET (ETo) file
   project.ETo
   './'
   1.3 Rain (PLU) file
   project.PLU
   './'
   1.4 Atmospheric CO2 concentration (CO2) file
   MaunaLoa.CO2
   'SIMUL/'
-- 2. Calendar (CAL) file
   project.CAL
   './'
-- 3. Crop (CRO) file
   project.CRO
   './'
-- 4. Irrigation management (IRR) file
   (None)
   (None)
-- 5. Field management (MAN) file
   project.MAN
   './'
-- 6. Soil profile (SOL) file
   project.SOL
   './'
-- 7. Groundwater table (GWT) file
   project.GWT
   './'
-- 8. Initial conditions (SW0) file
   project.SW0
   './'
-- 9. Off-season conditions (OFF) file
   (None)
   (None)
-- 10. Field data (OBS) file
   (None)
   (None)
